markets:
  exmo:
    api_key: "K-1612708cdd3c6e2ea35c4fd61dc570e338597a1c"
    secret: "S-87e72fd2b0db2783a424f8fb2255f29c5ddc2be1"
    history: "https://api.exmo.com/v1.1/candles_history?symbol=BTC_USD&resolution=$r&from=$f&to=$t"
    #history: 'https://api.exmo.com/v1.1/candles_history?symbol=BTC_USD&resolution=5&from=1593126150&to=1593817350'
    hours_since_today: 48
    resolution: 5